### ISSUE TITLE
A consistent vocabulary for describing common features:

### ISSUE THREAD

**Issue by psytek** [marcoEDU/Hackspaces.org-Redesign#15]

**Comment by psytek** [comment]
What are the hours for this space?

Is a membership required?

What are the costs

Are there tests or certifications required?

**Comment by glowingkitty** [comment]
good points :) however... what you describe sounds like important details for makerspaces (where people pay a membership to get access to the machines and rooms). Hackspaces, however, are by definition open to everyone (without any membership fee). As long as people are excellent to each other.
But the question for opening hours is indeed important! Especially since every hackspace has a different way of dealing with it. Some define open hours when people can visit, others are open to the public only on specific events, others have a chat where one can ask if the space is open for example - or a system on their website that says the space is open.
Definitely need to consider all those options for the new hackspaces.org.
